# Generated by Django 5.1.4 on 2024-12-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='Mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
