# Generated by Django 5.1.4 on 2024-12-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_alter_studentdb_age_alter_studentdb_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
