# Generated by Django 5.1.4 on 2024-12-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stud_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Class', models.IntegerField(blank=True, null=True)),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('College', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
